In [1]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

In [2]:
#pkg = mp.jupyter.open_package()
pkg = mp.jupyter.open_source_package()
pkg

# Post-Secondary Enrollment
`cde.ca.gov-postsec_enroll-1.2.3` Last Update: 2022-06-10T16:54:24

_Downloadable data about the College-Going Rate (CGR) for California high school completers disaggregated by race/ethnicity, student group, and academic year._


College-Going Rate (CGR) for California high school completers 12 months and 16
months after high school completion reported by race/ethnicity, student group,
and academic year.
## Documentation Links

* [College-Going Rate](https://www.cde.ca.gov/ds/ad/cgrinfo.asp) High-level overview of the CGR data sources, DataQuest reports, downloadable files, definitions, and rules helpful to understanding the CGR data reports and downloadable data files.
* [Using the CGR Data File](https://www.cde.ca.gov/ds/ad/usingcgr.asp) This page explains how to effectively use the sub-setting variables included in this CGR data file to obtain the desired counts.
* [Home Page](https://www.cde.ca.gov/ds/ad/pse.asp)
* [Data Dictionary](https://www.cde.ca.gov/ds/ad/fscgr16.asp) Field descriptions for the 16 month file



## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)
* **Origin** [Data Reporting Office](mailto:dro@cde.ca.gov), [California Department of Education](https://www.cde.ca.gov)

## Resources

* ** [cgr](notebooks/extract.ipynb#cgr)**. College Going Rate

## References
<ul><li> <strong><a href="https://www3.cde.ca.gov/demo-downloads/cgr/cgr12mo18.txt#target_format=tsv">cgr12mo18</a></strong>. 12 Month CGR 2018</li><li> <strong><a href="https://www3.cde.ca.gov/demo-downloads/cgr/cgr12mo17.txt#target_format=tsv">cgr12mo17</a></strong>. 12 Month CGR 2017</li><li> <strong><a href="https://www3.cde.ca.gov/demo-downloads/cgr/cgr12mo16.txt#target_format=tsv">cgr12mo16</a></strong>. 12 Month CGR 2016</li><li> <strong><a href="https://www3.cde.ca.gov/demo-downloads/cgr/cgr12mo15.txt#target_format=tsv">cgr12mo15</a></strong>. 12 Month CGR 2015</li><li> <strong><a href="https://www3.cde.ca.gov/demo-downloads/cgr/cgr16mo17.txt#target_format=tsv">cgr16mo17</a></strong>. 16 Month CGR 2017</li><li> <strong><a href="https://www3.cde.ca.gov/demo-downloads/cgr/cgr16mo16.txt#target_format=tsv">cgr16mo16</a></strong>. 16 Month CGR 2016</li><li> <strong><a href="https://www3.cde.ca.gov/demo-downloads/cgr/cgr16mo15.txt#target_format=tsv">cgr16mo15</a></strong>. 16 Month CGR 2015</li><ul>

In [3]:
cgr12 = pd.concat([ r.dataframe(parse_dates=False) for r in pkg.references() if r.group == '12' ])
cgr12.head().T

/Users/eric/proj/metatab-dev/metapack-dev/metapack/src/metapack/terms.py:707: UserWarning: Failed to set parse dates . Trying again without parse_dates configuration
  warnings.warn('Failed to set parse dates . Trying again without parse_dates configuration')

,0,1,2,3,4
ï»¿AcademicYear,2017-18,2017-18,2017-18,2017-18,2017-18
AggregateLevel,C,C,C,C,C
CountyCode,01,01,01,01,01
DistrictCode,,,,,
SchoolCode,,,,,
CountyName,Alameda,Alameda,Alameda,Alameda,Alameda
DistrictName,,,,,
SchoolName,,,,,
CharterSchool,No,Yes,No,Yes,All
AlternativeSchoolAccountabilityStatus,Yes,Yes,No,No,Yes
ReportingCategory,GF,GF,GF,GF,GF
CompleterType,TA,AGY,AGY,AGY,NGC
High School Completers,571,15,4067,687,*
Enrolled In College - Total (12 Months),204,8,3515,542,*
College Going Rate - Total (12 Months),35.7,53.3,86.4,78.9,*
Enrolled In-State (12 Months),201,8,2877,494,*
Enrolled Out-of-State (12 Months),3,0,638,48,*
Not Enrolled In College (12 Months),367,7,552,145,*
Enrolled UC (12 Months),2,0,888,165,*
Enrolled CSU (12 Months),7,1,906,185,*
Enrolled CCC (12 Months),185,3,804,111,*
Enrolled In-State Private (2 and 4 Year) (12 Months),7,4,279,33,*
Enrolled Out-of-State 4-Year College (Public/Private) (12 Months),2,0,626,48,*
Enrolled Out-of-State 2-Year College (Public/Private) (12 Months),1,0,12,0,*

In [4]:
cgr16 = pd.concat([ r.dataframe() for r in pkg.references() if r.group == '16' ])
cgr16.head().T

/Users/eric/proj/metatab-dev/metapack-dev/metapack/src/metapack/terms.py:707: UserWarning: Failed to set parse dates . Trying again without parse_dates configuration
  warnings.warn('Failed to set parse dates . Trying again without parse_dates configuration')

,0,1,2,3,4
ï»¿AcademicYear,2016-17,2016-17,2016-17,2016-17,2016-17
AggregateLevel,C,C,C,C,C
CountyCode,01,01,01,01,01
DistrictCode,,,,,
SchoolCode,,,,,
CountyName,Alameda,Alameda,Alameda,Alameda,Alameda
DistrictName,,,,,
SchoolName,,,,,
CharterSchool,No,Yes,All,Yes,All
AlternativeSchoolAccountabilityStatus,Yes,Yes,All,No,All
ReportingCategory,GF,GF,GF,GF,GF
CompleterType,NGC,TA,NGC,AGY,TA
High School Completers,*,17,36,660,7361
Enrolled In College - Total (16 Months),*,9,20,528,5814
College Going Rate - Total (16 Months),*,52.9,55.6,80.0,79.0
Enrolled In-State (16 Months),*,9,19,470,5043
Enrolled Out-of-State (16 Months),*,0,1,58,771
Not Enrolled In College (16 Months),*,8,16,132,1547
Enrolled UC (16 Months),*,0,1,125,1030
Enrolled CSU (16 Months),*,0,0,185,1272
Enrolled CCC (16 Months),*,9,18,127,2393
Enrolled In-State Private (2 and 4 Year) (16 Months),*,0,0,33,348
Enrolled Out-of-State 4-Year College (Public/Private) (16 Months),*,0,0,57,732
Enrolled Out-of-State 2-Year College (Public/Private) (16 Months),*,0,1,1,39

In [5]:
common_cols =  [c for c in cgr12.columns if c in set(cgr12) & set(cgr16)] # Comprehension in order to get same order as in dataframe
cols12 = [c for c in cgr12.columns if c in set(cgr12) ^ set(cgr16)]
cols16 = [c for c in cgr16.columns if c in set(cgr12) ^ set(cgr16)]
cols16

['Enrolled In College - Total (16 Months)',
 'College Going Rate - Total (16 Months)',
 'Enrolled In-State (16 Months)',
 'Enrolled Out-of-State (16 Months)',
 'Not Enrolled In College (16 Months)',
 'Enrolled UC (16 Months)',
 'Enrolled CSU (16 Months)',
 'Enrolled CCC (16 Months)',
 'Enrolled In-State Private (2 and 4 Year) (16 Months)',
 'Enrolled Out-of-State 4-Year College (Public/Private) (16 Months)',
 'Enrolled Out-of-State 2-Year College (Public/Private) (16 Months)']

In [6]:
t = cgr12.merge(cgr16, on=common_cols, how='outer')

In [7]:
len(cgr12), len(cgr16), len(t)

(1827370, 1363573, 1827526)

In [8]:
t = t.rename(columns={list(t.columns)[0]:'AcademicYear'}) # It's got unicode crap in the name
def repl(v):
    vo = v
    v = v.replace('(16 Months)','16m')
    v = v.replace('(12 Months)','12m')
    v = v.replace('In-State','In')
    v = v.replace('Out-of-State','Out')
 
    return v
    
[repl(c) for c in t.columns]

['AcademicYear',
 'AggregateLevel',
 'CountyCode',
 'DistrictCode',
 'SchoolCode',
 'CountyName',
 'DistrictName',
 'SchoolName',
 'CharterSchool',
 'AlternativeSchoolAccountabilityStatus',
 'ReportingCategory',
 'CompleterType',
 'High School Completers',
 'Enrolled In College - Total 12m',
 'College Going Rate - Total 12m',
 'Enrolled In 12m',
 'Enrolled Out 12m',
 'Not Enrolled In College 12m',
 'Enrolled UC 12m',
 'Enrolled CSU 12m',
 'Enrolled CCC 12m',
 'Enrolled In Private (2 and 4 Year) 12m',
 'Enrolled Out 4-Year College (Public/Private) 12m',
 'Enrolled Out 2-Year College (Public/Private) 12m',
 'Enrolled In College - Total 16m',
 'College Going Rate - Total 16m',
 'Enrolled In 16m',
 'Enrolled Out 16m',
 'Not Enrolled In College 16m',
 'Enrolled UC 16m',
 'Enrolled CSU 16m',
 'Enrolled CCC 16m',
 'Enrolled In Private (2 and 4 Year) 16m',
 'Enrolled Out 4-Year College (Public/Private) 16m',
 'Enrolled Out 2-Year College (Public/Private) 16m']

In [9]:
cgr = t

In [10]:
for c in cgr.columns:
    try:
        cgr[c] = pd.to_numeric(cgr[c].replace('*','NaN').replace('NaN',np.nan) )
        cgr[c] = cgr[c].astype('Int64')
        
        try:
            cgr[c] = cgr[c].astype('int')
        except Exception as e:
            cgr[c] = cgr[c].astype('float') # Has missing values, so can't be an int
        
    except ValueError:
        print(f"Failed to convert to numeric: {c}")
    except TypeError:
        print(f"Failed to convert to integer: {c}")

Failed to convert to numeric: AcademicYear
Failed to convert to numeric: AggregateLevel
Failed to convert to numeric: CountyName
Failed to convert to numeric: DistrictName
Failed to convert to numeric: SchoolName
Failed to convert to numeric: CharterSchool
Failed to convert to numeric: AlternativeSchoolAccountabilityStatus
Failed to convert to numeric: ReportingCategory
Failed to convert to numeric: CompleterType
Failed to convert to integer: College Going Rate - Total (12 Months)
Failed to convert to integer: College Going Rate - Total (16 Months)

In [11]:
cgr.ReportingCategory.value_counts()

TA    166370
GM    156928
SS    153221
GF    152540
RH    146810
RW    143933
SD    125382
SE    110210
RB     99883
RA     91036
RT     87568
SH     83052
RF     72432
SF     62559
RI     60094
RP     49514
RD     33069
SM     32925
Name: ReportingCategory, dtype: int64

In [13]:
cgr.dtypes

AcademicYear                                                          object
AggregateLevel                                                        object
CountyCode                                                             Int64
DistrictCode                                                           Int64
SchoolCode                                                             Int64
CountyName                                                            object
DistrictName                                                          object
SchoolName                                                            object
CharterSchool                                                         object
AlternativeSchoolAccountabilityStatus                                 object
ReportingCategory                                                     object
CompleterType                                                         object
High School Completers                                                 Int64
Enrolled In College - Total (12 Months)                                Int64
College Going Rate - Total (12 Months)                               float64
Enrolled In-State (12 Months)                                          Int64
Enrolled Out-of-State (12 Months)                                      Int64
Not Enrolled In College (12 Months)                                    Int64
Enrolled UC (12 Months)                                                Int64
Enrolled CSU (12 Months)                                               Int64
Enrolled CCC (12 Months)                                               Int64
Enrolled In-State Private (2 and 4 Year) (12 Months)                   Int64
Enrolled Out-of-State 4-Year College (Public/Private) (12 Months)      Int64
Enrolled Out-of-State 2-Year College (Public/Private) (12 Months)      Int64
Enrolled In College - Total (16 Months)                                Int64
College Going Rate - Total (16 Months)                               float64
Enrolled In-State (16 Months)                                          Int64
Enrolled Out-of-State (16 Months)                                      Int64
Not Enrolled In College (16 Months)                                    Int64
Enrolled UC (16 Months)                                                Int64
Enrolled CSU (16 Months)                                               Int64
Enrolled CCC (16 Months)                                               Int64
Enrolled In-State Private (2 and 4 Year) (16 Months)                   Int64
Enrolled Out-of-State 4-Year College (Public/Private) (16 Months)      Int64
Enrolled Out-of-State 2-Year College (Public/Private) (16 Months)      Int64
dtype: object